# Generated by Django 4.2 on 2024-09-16 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('rus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кнопка (русский)')),
                ('heb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кнопка (иврит)')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'кнопка',
                'verbose_name_plural': 'кнопки',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='ChannelForEmployers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('is_active', models.BooleanField(default=True, verbose_name='Участвует в рассылке?')),
            ],
            options={
                'verbose_name': 'канал для работодателей',
                'verbose_name_plural': 'каналы для работодателей (с сотрудниками)',
            },
        ),
        migrations.CreateModel(
            name='ChannelForWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('is_active', models.BooleanField(default=True, verbose_name='Участвует в рассылке?')),
            ],
            options={
                'verbose_name': 'канал для работников',
                'verbose_name_plural': 'каналы для работников (с вакансиями)',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник телеграм')),
                ('name', models.CharField(default='Company', max_length=150, verbose_name='Имя/название компании')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'работодатель',
                'verbose_name_plural': 'работодатель',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата (от ₪/час)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_rus', models.TextField(blank=True, default=None, null=True, verbose_name='Описание (русский)')),
                ('notifications', models.BooleanField(default=False, verbose_name='Подписан на уведомления?')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.employer', verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=200, unique=True, verbose_name='TG id фото')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('rus', models.CharField(max_length=100, verbose_name='Профессия (русский)')),
                ('heb', models.CharField(max_length=100, verbose_name='Профессия (иврит)')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'профессия',
                'verbose_name_plural': 'профессии',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('rus', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст (русский)')),
                ('heb', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст (иврит)')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'тексты',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('target', models.CharField(choices=[('1', 'Работник'), ('2', 'Работодатель')], max_length=10, verbose_name='Тип пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник телеграм')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона')),
                ('passport_photo_tg_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='TG id паспорта')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('about_heb', models.TextField(blank=True, default=None, null=True, verbose_name='О себе (иврит)')),
                ('min_salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата (от ₪/час)')),
                ('notifications', models.BooleanField(default=False, verbose_name='Подписан на уведомления?')),
                ('is_searching', models.BooleanField(default=True, verbose_name='В поисках работы?')),
                ('is_approved', models.BooleanField(blank=True, default=None, null=True, verbose_name='Аккаунт подтвержден?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('objects_photos', models.ManyToManyField(blank=True, related_name='objects_photos', to='core.objectphoto', verbose_name='Фото объектов')),
                ('occupations', models.ManyToManyField(blank=True, related_name='users', to='core.occupation', verbose_name='Профессии')),
                ('passport_photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото паспорта')),
            ],
            options={
                'verbose_name': 'работник',
                'verbose_name_plural': 'работники',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=5, verbose_name='Оценка')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв (русский)')),
                ('review_heb', models.TextField(blank=True, null=True, verbose_name='Отзыв (иврит)')),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reviews', to='core.employer', verbose_name='Работодатель, получивший отзыв')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaved_reviews', to='core.worker', verbose_name='Сотрудник, оставивший отзыв')),
            ],
            options={
                'verbose_name': 'отзыв работника',
                'verbose_name_plural': 'отзывы работников',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkerCooperationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(blank=True, default=None, null=True, verbose_name='Принят?')),
                ('is_proceeded', models.BooleanField(default=False, verbose_name='Отправлен в админ чат?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_proposals', to='core.employer', verbose_name='Работодатель, получивший запрос')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.job', verbose_name='Вакансия, вызвавшая запрос')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_proposals', to='core.worker', verbose_name='Работник, запросивший сотрудничество')),
            ],
            options={
                'verbose_name': 'предложение о сотрудничестве от работника',
                'verbose_name_plural': 'предложения о сотрудничестве от работников',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='occupations',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='core.occupation', verbose_name='Профессии'),
        ),
        migrations.CreateModel(
            name='EmployerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=5, verbose_name='Оценка')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв (русский)')),
                ('review_rus', models.TextField(blank=True, null=True, verbose_name='Отзыв (иврит)')),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaved_reviews', to='core.employer', verbose_name='Работодатель, оставивший отзыв')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reviews', to='core.worker', verbose_name='Сотрудник, получивший отзыв')),
            ],
            options={
                'verbose_name': 'отзыв работодателя',
                'verbose_name_plural': 'отзывы работодателей',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmployerCooperationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(blank=True, default=None, null=True, verbose_name='Принят?')),
                ('is_proceeded', models.BooleanField(default=False, verbose_name='Отправлен в админ чат?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_proposals', to='core.employer', verbose_name='Работодатель, запросивший сотрудничество')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_proposals', to='core.worker', verbose_name='Работник, получивший запрос')),
            ],
            options={
                'verbose_name': 'предложение о сотрудничестве от работодателей',
                'verbose_name_plural': 'предложения о сотрудничестве от работодателей',
                'ordering': ('-updated_at',),
            },
        ),
    ]
