# Generated by Django 4.2 on 2024-09-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_area_remove_job_occupations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='selfie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TG id селфи'),
        ),
    ]
