# Generated by Django 4.2 on 2024-09-16 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('1', 'Индивидуальное'), ('2', 'Всем работникам'), ('3', 'Всем работодателям'), ('4', 'Всем пользователям')], max_length=30, verbose_name='Тип уведомления')),
                ('text_rus', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст уведомления (русский)')),
                ('text_heb', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст уведомления (иврит)')),
                ('notify_time', models.DateTimeField(help_text='Указывается в UTC (-3 от МСК).', verbose_name='Время уведомления')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Рассылка валидна?')),
                ('started', models.BooleanField(default=False, verbose_name='Рассылка началась?')),
                ('notified', models.BooleanField(blank=True, default=None, null=True, verbose_name='Успешно?')),
                ('success_users', models.IntegerField(default=0)),
                ('total_send_users', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
                ('user', models.ForeignKey(blank=True, help_text='Учитывается только если выбран тип "индивидуальное"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'уведомление пользователей',
                'verbose_name_plural': 'уведомления пользователей',
                'ordering': ('-notify_time',),
            },
        ),
        migrations.CreateModel(
            name='LinkButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_rus', models.CharField(max_length=50, verbose_name='Текст (русский)')),
                ('text_heb', models.CharField(max_length=50, verbose_name='Текст (иврит)')),
                ('link', models.CharField(help_text='Обязательно должна содержать "https://"', max_length=1024, verbose_name='Ссылка')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='notifications.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'кнопка с ссылкой',
                'verbose_name_plural': 'кнопки с ссылками',
                'ordering': ('my_order',),
            },
        ),
    ]
